tombstone success
cnosdb/cnosdb pull request #152
Opened 2022-03-14 15:14 UTC by 120L020410

Closes #

Describe your proposed changes here.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Tests pass
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [x] Signed [CLA](https://cla-assistant.io/cnosdb/cnosdb) (if not already signed)

2022-03-14 15:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cnosdb/cnosdb?pullRequest=152) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cnosdb/cnosdb?pullRequest=152) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cnosdb/cnosdb?pullRequest=152) it.</sub>

2022-03-15 03:22 UTC, IvanGao01 commented
[check failed](https://github.com/cnosdb/cnosdb/runs/5547389585?check_suite_focus=true) , can't merge

2022-03-15 13:36 UTC, xiaobaiAlan commented
change one of the packages

2022-03-16 07:41 UTC, IvanGao01 requested changes
The latest code is no longer available ".vendor/db/tsdb/engine/tsm1/tombstone/tombstone.go"
And it has been moved to "vend/db/tsdb/engine/tsm1/tombstone. go" and you need to pull the latest code and submit it

2022-03-20 12:27 UTC, closed without merging